language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - cd merge/tests && ./gendata.sh && cd ../..
script:
    - pwd
    - find
    - ls merge/tests/data/A
    - ls merge/tests/data/B
    - nosetests -v
